//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.KhachThues = new HashSet<KhachThue>();
        }
    
        public int maPhong { get; set; }
        public string tenPhong { get; set; }
        public Nullable<int> giaThue { get; set; }
        public Nullable<int> tienNo { get; set; }
        public Nullable<int> dienTich { get; set; }
        public Nullable<System.DateTime> ngayVao { get; set; }
        public Nullable<System.DateTime> ngayHet { get; set; }
        public string tinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachThue> KhachThues { get; set; }
    }
}
