//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BaoCaoTinhTrang
    {
        public int maNha { get; set; }
        public string tenNha { get; set; }
        public Nullable<int> tongPhong { get; set; }
        public Nullable<int> soPhongDangThue { get; set; }
        public Nullable<int> soPhongNoTien { get; set; }
        public Nullable<int> tongKhachThue { get; set; }
        public Nullable<decimal> tyLePhongDangThue { get; set; }
        public Nullable<decimal> tyLePhongNoTien { get; set; }
    }
}
