//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BaoCaoTaiChinh
    {
        public int maNha { get; set; }
        public string tenNha { get; set; }
        public string thangNam { get; set; }
        public Nullable<int> tongTienDien { get; set; }
        public Nullable<int> tongTienNuoc { get; set; }
        public Nullable<int> tongVeSinh { get; set; }
        public Nullable<int> tongInternet { get; set; }
        public Nullable<int> tongTienPhong { get; set; }
        public Nullable<int> tongDaThu { get; set; }
    }
}
